<?php

 /*               DO NOT EDIT THIS FILE

  Edit the file in the MyComponent config directory
  and run ExportObjects

 */


$packageNameLower = basename(__FILE__,'.config.php');
return include MODX_ASSETS_PATH.'mycomponents/'.$packageNameLower.'/'.$packageNameLower.'.config.php';